#
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: shopdemo
    restart: always
    command: --check-caps false
    ports: 
      - 52773:52773

    volumes:
      - ./:/irisdev/app    

    environment:
    - TZ=JST-9
